### ISSUE TITLE
Tox tests do not work

### ISSUE THREAD

**Issue by tillea** [MikkelSchubert/paleomix#14]
Hi,
when trying to upgrade the paleomix Debian package to version 1.2.12 I also wanted to run the topx test suite.  Unfortunately I get:

    $ tox
    GLOB sdist-make: /home/tillea/debian-maintain/alioth/debian-med_git/paleomix/setup.py
    ERROR: invocation failed (exit code 1), logfile: /home/tillea/debian-maintain/alioth/debian-med_git/paleomix/.tox/log/tox-0.log
    ERROR: actionid: tox
    msg: packaging
    cmdargs: ['/usr/bin/python3', local('/home/tillea/debian-maintain/alioth/debian-med_git/paleomix/setup.py'), 'sdist', '--formats=zip', '--dist-dir', local('/home/tillea/debian-maintain/alioth/debian-med_git/paleomix/.tox/dist')]
    env: None
    
    ERROR: Python version 2.7.x required!
           Current version is v3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
    
    ERROR: FAIL could not package project - v = InvocationError('/usr/bin/python3 .../debian-med_git/paleomix/setup.py sdist --formats=zip --dist-dir .../debian-med_git/paleomix/.tox/dist (see .../debian-med_git/paleomix/.tox/log/tox-0.log)', 1)

The machine where I tried to run this test has

    $ python --version
    Python 2.7.13
    $ python3 --version
    Python 3.5.3

Any hint what might went wrong here?

BTW, in Debian it is considered a good idea to move to Python3 rather sooner than later - but the interpreter that you call with simply `python` will remain the 2.x series of Python.

Kind regards, Andreas.

**Comment by Exzyelph** [comment]
Hi Andreas,
Thank you very much for the report.

Tox is failing because of a check I originally added to prevent people accidentally installing the software using python3. However, that also triggers when you try to run tox installed using python3, which was not the intention. I'm pushing a patch that removes the check entirely, since the current recommended installation method is 'pip', and has been so for quite a while.

Cheers,
 Mikkel
