### ISSUE TITLE
Java issue with an updated openjdk version

### ISSUE THREAD

**Issue by flaviode** [MikkelSchubert/paleomix#33]
Hi, I run BAM pipeline but it returns:

Building BAM pipeline ...
  - Validating prefixes ...
Running BAM pipeline ...
  - Checking file dependencies ...
  - Checking for required executables ...
  - Checking version requirements ...
    - Checking version of 'JAVA Runtime Environment' ...
Program may be broken or a version not supported by the
pipeline; please refer to the PALEOMIX documentation.

    Required:       at least v1.6.x
    Search string:  'java version "(\\d+)[\\._](\\d+)'
---------------------- Command output ----------------------
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

I guess this version is updated: how can I figure out this issue, without changing the openjdk version?

Thanks

**Comment by MikkelSchubert** [comment]
Hi,

You appear to be using a version of PALEOMIX that is very, *very* old:
The particular issue you are running into was fixed four years ago, and the version check was then completely removed two years ago because of related issues. So upgrading to a newer version of PALEOMIX (e.g. v1.2.14) should fix it. If it doesn't, then feel free to open another issue.

Best,
 Mikkel
