### ISSUE TITLE
Phylo pipeline "unknown command"

### ISSUE THREAD

**Issue by 974ben** [MikkelSchubert/paleomix#48]
Hello,

I am trying to run the phylo pipeline with the latest version of paleomix - 1.3.7

I've tried lots of variants on the same command, including using example documentation as well as my own own makefile, but consistently get the same error message:

 ERROR unknown command 'genotyping'

Just one example of the commands yielding this error is:
paleomix phylo_pipeline genotyping+msa+phylogeny makefile.yaml

I've checked and I believe I have all the correct development files installed.
Could you advise what might be causing this error?

Many thanks,
Ben

**Comment by MikkelSchubert** [comment]
Hi Ben,

Sorry for the trouble and thank you for the report!

It seems that I made a mistake while writing the documentation.
Instead of `genotyping` it should be `genotype`, as in

     paleomix phylo_pipeline genotype+msa+phylogeny makefile.yaml

However, I have to caution that the phylo pipeline is deprecated and slated for removal in the next major release of paleomix (2.0) sometime in the future, due to lack of use and hence development. However, I'll gladly answer your questions and help with any issues you run into.

Best,
Mikkel

**Comment by MikkelSchubert** [comment]
I've released a version of paleomix that fixes this (v1.3.8).
Once again thank you for reporting this and do let me know if you run into any other issues.

Best,
Mikkel
