### ISSUE TITLE
conda environment perpetually solving during installation

### ISSUE THREAD

**Issue by laurenhamm** [MikkelSchubert/paleomix#50]
When using the instructions for installing paleomix in a conda environment, the "solving environment" step takes many hours and never finishes, despite many work arounds. Is there something that I am missing? I would prefer to set up everthing an a conda enviroment since I am doing remote htc work.

**Comment by MikkelSchubert** [comment]
It's definitely not supposed to take that long.
I'll look into it before the end of the week and get back to you.

Best,
Mikkel

**Comment by laurenhamm** [comment]
Thanks!
I was able to get it to run once I specific specific versions for all the channels/dependencies, but that resulted in ~100 conflicts across packages. Currently trying different combinations to see if I can resolve this issue

**Comment by MikkelSchubert** [comment]
Have you tried using [mamba](https://github.com/mamba-org/mamba) instead of vanilla conda?
If not, then I'd highly recommend it. Mamba only takes a few seconds resolve the environment on my system.

I think the problem is that I've consistently been using mamba for a long time, so I didn't notice how bad it had gotten with regular conda. I'll try to see if I cannot improve the situation without having to specify exact versions for everything, but that might end up being the solution.

**Comment by MikkelSchubert** [comment]
I've attached an alternative conda environment to this message, which should solve the problem by pinning the major and minor versions, but not the point release (${major}.${minor}.${point}). It still takes about 4-5 minutes to resolve with conda on my machine, compared to about 2-3 seconds with mamba, which is not optimal, but it's usable. I could reduce it further by pinning the point releases, but that would result in people missing out on bug-fixes in dependencies in between the (very irregular) paleomix releases.

If mamba isn't an option, or if you have time to test it anyway, then please let me know if it works for you.

[paleomix_1_3_8.yaml.txt](https://github.com/MikkelSchubert/paleomix/files/11931357/paleomix_1_3_8.yaml.txt)

**Comment by laurenhamm** [comment]
I was able to

**Comment by laurenhamm** [comment]
I got it to work! Thanks!
