### ISSUE TITLE
time elapsed reset by using function keys

### ISSUE THREAD

**Issue by ginolhac** [MikkelSchubert/paleomix#9]
In `v1.2.5` in the screen output,
the time elapsed is updated, a feature I like:
`14:02:34 Running 3 tasks using ~3 of max 6 threads; 143 done of 166 tasks in 2:03s`

after using `l` to list (or increasing / decreasing # cores to use), the elapsed time is reset

`14:11:11 Running 3 tasks using ~3 of max 6 threads; 143 done of 166 tasks in 0s`

would it be possible to leave this time counter aside from using keys?

**Comment by MikkelSchubert** [comment]
This is a bug in the reporting code, but it should only happen when you use the 'l' command, since that creates a temporary progress reporter, and it should not affect the running time reported for subsequent status updates, including when changing threads. Can you check if this is the case? Otherwise there's another bug I am missing. 

Regardless, I'll add a fix for this in the next version of PALEOMIX.

**Comment by ginolhac** [comment]
I can confirm the final reported time is correct.
Actually, when the progress reporter is updated by paleomix it became correct again
`14:34:44 Running 3 tasks using ~3 of max 6 threads; 160 done of 166 tasks in 34:13s`

So, yes it is only when the refresh is manually activated
